name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./Backend
        file: ./Backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-backend:latest

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./Frontend
        file: ./Frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest

    - name: Deploy containers on EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-backend:latest
          docker stop backend || true
          docker rm backend || true
          docker run -d --name backend -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/my-backend:latest

          docker pull ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest
          docker stop frontend || true
          docker rm frontend || true
          docker run -d --name frontend -p 3000:80 ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest
